config/routes.rb
Rails.application.routes.draw do
  root "pages#search"
  get "movies/:id", to: "pages#show", as: :movie
  resources :movies, only: [:show]
  get "search", to: "pages#search", as: :search
  post "enable_analytics", to: "analytics#enable", as: :enable_analytics
  get  "analytics", to: "analytics#index"
  get  "history", to: "pages#history"
  get  "trend", to: "pages#trend"
  post  "sign_in", to: "users#sign_in"
  post  "sign_up", to: "users#sign_up"
  get   "sign_up", to: "pages#sign_up"
  get   "sign_in", to: "pages#sign_in"
  get "sign_out", to: "users#sign_out"
  get "delete_account", to: "users#delete_account"
  get "clear_history", to: "users#clear_user_history"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/searchable.rb
module Searchable
    extend ActiveSupport::Concern
  
    included do
      include Elasticsearch::Model
      include Elasticsearch::Model::Callbacks

      mapping do
        indexes :actors, type: :text
        indexes :title, type: :text
        indexes :description, type: :text
        indexes :genre, type: :keyword
        indexes :country, type: :keyword
      end
  
      def self.search(query)
        params = {
      query: {
        bool: {
          should: [
            { match: { title: { query: query, fuzziness: "AUTO"  }}},
            { match: { description: { query: query, fuzziness: "AUTO"  } }},
            { match: {country: query }},
          ],
        }
      },
    }
        self.__elasticsearch__.search(params)
      end
    end
  end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :visitor
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :visitor

  #return array of objects with params and count
  def self.searches
    select(:params)
      .where(path: "/search")
      .group(:params)
      .count
      .map do |name, count|
      {name: name, count: count}
      end
  end
  
end

app/models/movie.rb
class Movie < ApplicationRecord
    include Searchable
    has_many :searches, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :visitor
  has_one :movie, class_name: "Movie", foreign_key: "id", primary_key: "movie_id"
  
  #return array of objects with params and count
  def self.searches
    select(:params)
      .group(:params)
      .count
      .map do |name, count|
      {name: name, count: count}
      end
  end
  # return array of ojects with params and count ordered by count
  def self.searches_ordered
    searches.sort_by { |hsh| hsh[:count] }.reverse
  end
# return array of ojects with params and count ordered by count limited to 5
  def self.searches_ordered_limited
    searches_ordered[0..4]
  end


  #return current visitor last search params
  def self.last_search_params
    last_search.params
  end
  
  def self.last_search_param
    searches.order created_at: :desc 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :visits, class_name: "Visitor"
  has_many :searches, through: :visits,  dependent: :destroy
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :user, optional: true
  has_many :searches

  def self.last_search_params
    searches.last
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    @analytics = Search.searches_ordered_limited
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include TrackSearch
    before_action :start_analytics
     helper_method :current_user, :logged_in?
     
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/controllers/concerns/set_current_visitor.rb
module SetCurrentVisitor
  extend ActiveSupport::Concern

  included do
    before_action :set_current_visitor, if: :should_set_current_visitor?
  end

  private

  def create_current_visitor
    visitor = Visitor.create!(
      user_agent: request.user_agent
    )
    session[:visitor_id] = visitor.id

    visitor
  end

  def set_current_visitor
    Current.visitor ||= Visitor.find_by(id: session[:visitor_id]) || create_current_visitor
  end

  def should_set_current_visitor?
    session[:enable_analytics] == true
  end
end

app/controllers/concerns/track_search.rb
module TrackSearch
  extend ActiveSupport::Concern

  def track_search
    if session[:enable_analytics] == true
      return if event_params.blank? 
      CreateSearchJob.perform_later(
        visitor: Current.visitor,
        params: check(event_params)
      )
    end
  end

  def update_actual_search
    UpdateSearchJob.perform_later(
      visitor: Current.visitor,
      params: movie_params
    )
  end


  def start_analytics
    session[:enable_analytics] = true
  end

  private

 
  def  check(param)
    return if param.blank? 
    param
 end 

  def filter_sensitive_data(params)
    return if params.nil?
    ActiveSupport::ParameterFilter.new(
      Rails.application.config.filter_parameters
    ).filter(params)
  end

  def event_params
    params[:search]|| filter_sensitive_data(request.request_parameters.presence)
  end

  def movie_params
    params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include TrackSearch
  include SetCurrentVisitor
  before_action :track_search, only: [:search]
  before_action :update_actual_search, only: [:show]

  def search
    @most_searched = Search.searches_ordered_limited
    query = params[:search] || ""
    @results = Movie.search(query).results
  end
  
  def show
    @movie = Movie.find(params[:id])
  end

  def history
    if logged_in?
      @visitor_recent_search =  current_user.searches.includes(:movie).order(created_at: :desc).limit(10)
     else
       @visitor_recent_search = Current.visitor.searches.includes(:movie).order(created_at: :desc).limit(10)
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SetCurrentVisitor
  def sign_in
        user = User.find_by!(email: params[:email])
        if user&.authenticate(params[:password])
         set_current_user(user)
         Current.visitor.presence && Current.visitor.update!(user: user)
        redirect_to root_path
      end
    end

    def set_current_user(user)
      session[:user_id] = user.id
    end

      def sign_up
        user = User.create!(user_params)
        set_current_user(user)
        Current.visitor.presence && Current.visitor.update!(user: user)
        redirect_to root_path
      end    

      def sign_out
        session[:user_id] = nil
        redirect_to root_path
      end

      def clear_device_history
        Current.visitor.searches.destroy_all
      end
      
      def clear_user_history
        Current.visitor.presence && Current.visitor.update!(user: nil)
        redirect_to root_path
      end

      def delete_account
        current_user.destroy
        session[:user_id] = nil
        Current.visitor.update!(user: nil)
        redirect_to root_path
      end
      private

      def user_params
          params.permit(:username, :email, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/index.html.erb
<div class="wrapper">
<h2 class="mt-10 text-4xl text-white font-bold text-center"> Top 5 of what people searched for</h2>


    <table class="mt-14 table-fixed text-white text-center drop-shadow-2xl rounded-bl-3xl rounded-tr-3xl">
    <thead>
  <tr class="bg-yellow-400 hover:text-black hover:bg-yellow-500 border-b-2">
    <th class="p-5 m-2 rounded-bl-3xl">Search Item</th>
    <th class="p-5 m-2 rounded-tr-3xl">Count</th>
  </tr>
  </thead>
<%@analytics.each_with_index do |search,index| %>
  <tbody>
    <tr class="bg-lime-500 hover:bg-lime-600 hover:text-black border-t-2">
        <td class="p-5 rounded-bl-3xl"><%= search[:name] %></td>
        <td class="p-5 rounded-tr-3xl"><%= search[:count] %></td>
    </tr>
    </tbody>
    <% end %>
    </table>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body class="bg font-mono">
    <%= yield %>
    <% unless session[:enable_analytics] == true%>
      <%= button_to "Enable Analytics", enable_analytics_path %>
    <% end %>
  </body>
</html>

app/views/pages/_search_result.html.erb
<div class="row search top-5">
  <div class="col hover:bg-gray-400 w-full px-3 py-4">
  <%= link_to "#{result.title} - #{result.genre}", movie_path(result.id) %><br />
  </div>
</div>

app/views/pages/history.html.erb
<h2 class="mt-10 text-4xl text-white font-bold text-center">Your Recent Searches</h2>
<% @visitor_recent_search.map  do |search|%>

<div class="wrapper bg-yellow-400 w-3/6 h-5/6 mt-8 rounded-full hover:bg-yellow-500 hover:text-white">Searched <span class="bold"><%=search.params%></span>
  <% if search.movie.present?%>
  <div>and found <%=link_to search.movie.title, movie_path(search.movie)%></div>
  <% else %>
  <div>Movie not found</div>
  <% end %>
  </div>
<% end %>

<%if current_user%>
<%= link_to "delete history", clear_history_path%>

<%end%>

app/views/pages/search.html.erb
<%# Section for sign in and sign out %>
<div><% if  current_user %>
  <%# At line 3 instead of email access name %>
  <div class="">
   <p class="text-yellow-500 font-mono text-2xl float-left font-extrabold leading-10 ml-2 capitalize"><%= current_user.email%></p>
   <p class="float-right p-2 text-yellow-400 font-bold mr-3 mt-3 mb-5"><%= link_to "Sign Out", sign_out_path %></p>
  </div>
<% else %>
  <div class="float-right p-2 text-yellow-400 font-bold mr-3 mt-3 mb-5"><%= link_to "Sign In", sign_in_path %></div>
<% end %> 

<%# Section for navigation bar %>
<div class="flex flex-row float-right text-yellow-400 mb-5 mt-3 font-bold">
  <p class="p-2"><%=link_to "Search History ",history_path%></p>
  <p class="p-2"><%=link_to "Analytics",analytics_path%></p>
</div><br>
</div>
<%# Section for Search form %>
<%# <div class="flex flex-col justify-center p-10 font-bold"> %>
<div class="wrapper mt-10 block">
  <%= form_with(url: search_path, method: :get, data: {controller: "search-form",search_form_target:"form",turbo_frame: "articles"}) do |form| %>
  <h1 class="text-white text-4xl text-center p-7"><%= form.label :query, "Movies Engine" %></h1>
    <div class="flex flex-row-reverse space-x-3 justify-center mt-10">
    <div class="hover:text-white ml-3 px-6 py-3 bg-yellow-400 rounded-full cursor-pointer hover:bg-yellow-600 focus:ring-4 ring-0 focus:ring-yellow-100"><%= form.submit 'Search'%></div>
      <div class="relative">
      <div data-controller="showhide">
        <div><%= form.text_field :search, class: "overflow-hidden py-3 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" , data: {action: "input->search-form#search"}, value: params[:search] %></div>
          <%# Section for search results %>
          <div data-showhide-target="output" class="absolute top-9 right-2 w-85 rounded-lg bg-white -z-10 h-96 overflow-auto touch-auto scroll-mr-5 scroll-px-1">
            <%= turbo_frame_tag "articles" do %> 
              <div class="search overflow-auto touch-pan-y"><%=render partial: 'search_result', collection: @results, as: :result, class: "py-2 mt-4" %></div> 
            <% end %> 
          </div>
        </div>
    </div>
      <% if  !current_user %>
        <p class="absolute text-center mt-20 text-yellow-500 font-bold m-10 -z-20">Hey there anonymous user sign in to manage your analytics</p>
      <% end %>
  <% end %>
  
</div>
</div>



<%# Section for trending %>
<div class="flex flex-row ml-5 absolute bottom-5 left-0 -z-20">
  <span class="h-3 w-3 px-2 py-1 mb-2">
    <span class="animate-ping absolute bottom-0 left-0 inline-flex h-10 w-10 rounded-full bg-yellow-400 opacity-65 item-center"></span>
    <span class="relative inline-flex rounded-full h-3 w-3 bg-yellow-500 rounded-full"></span>
  </span>
  <p class="px-2 py-1 text-xl text-yellow-600">Trending Searches:</p>
    <% @most_searched.each do |search| %>
     <div class="bg-yellow-400 ml-1 px-3 py-1 rounded-bl-2xl rounded-tr-2xl hover:bg-yellow-600 hover:text-white drop-shadow-2xl"> <%=search[:name] %></div>
    <% end %>
</div>


 

app/views/pages/show.html.erb
<h2 class="mt-10 text-4xl text-white font-bold text-center"><%= @movie.title %></h2>

<div class="wrapper bg-yellow-400 w-4/6 mt-8 drop-shadow-2xl rounded-bl-3xl rounded-tr-3xl hover:bg-yellow-500">
  <h3 class="text-2xl font-bold p-5">genre </h3>
    <p class="pr-5 pl-5 text-salt-500"><%= @movie.genre %></p>
  <h3 class="text-2xl font-bold p-5">country </h3>
    <p class="pr-5 pl-5 text-salt-500"><%= @movie.country %></p>
  <h3 class="text-2xl font-bold p-5">actors </h3>
    <p class="pr-5 pl-5 text-salt-500"><%= @movie.actors %></p>
  <h3 class="text-2xl font-bold p-5">synopsis </h3>
    <p class="pr-5 pl-5 pb-5 text-salt-500"><%= @movie.description %></p>
</div>



 

app/views/pages/sign_in.html.erb
<div class="wrapper bg-yellow-400 w-2/6 h-96 mt-24 rounded-bl-3xl rounded-tr-3xl hover:bg-yellow-500 hover:text-white">
<div class="p-8 mt-5 font-bold">
<h2 class="text-center mb-10 font-bold text-2xl">Sign In</h2>
<%= form_with(url: "/sign_in" ,method: :post,local: true) do |f| %>
   <div><%= f.label :email %><br>
      <div><%= f.text_field :email, class: "text-black py-2 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" %>
   </div>
   
   <div><%= f.label :password %>
      <%= f.password_field :password, class: "text-black py-2 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" %>
   </div>

   <div><%= f.submit "Sign in", class: "h-12 w-20 mt-3 text-center bg-lime-600 drop-shadow-2xl rounded-bl-3xl rounded-tr-3xl hover:bg-black hover:bg-lime-500" %></div>
<% end %>
<div class="mt-5"><p>Don't have an account? <%= link_to "Sign Up", sign_up_path %></p></div>
</div>
</div>

app/views/pages/sign_up.html.erb
<div class="wrapper bg-yellow-400 w-2/6 h-100 mt-24 rounded-bl-3xl rounded-tr-3xl hover:bg-yellow-500 hover:text-white">
<div class="p-8 mt-5 font-bold">
<h2 class="text-center mb-10 font-bold text-2xl">Sign Up</h2>
<div class="p-4"><%= form_with(url: "/sign_up" ,method: :post,local: true) do |f| %> 
  <%# Put a text field %>
  <%= f.label :email %>
  <%= f.text_field :email, class: "text-black py-2 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "text-black py-2 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "text-black py-2 px-4 rounded-full border ring-0 focus:ring-4 focus:ring-yellow-100 focus:shadow-none focus:border-yellow-400 focus:outline-none w-96" %>
  <%= f.submit "Create my account", class: "h-12 w-40 mt-3 text-center bg-lime-600 drop-shadow-2xl rounded-bl-3xl rounded-tr-3xl hover:bg-black hover:bg-lime-500" %>
<% end %>
</div>
</div>
</div>